global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'fastapi_crawler'
    # FastAPI HTTP endpoint for health check and /metrics
    static_configs:
      - targets: ['fastapi_crawler:8000'] # Target the internal container port for FastAPI HTTP
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121'] # Redis exporter running on port 9121

  - job_name: 'postgresql_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187'] # PostgreSQL exporter running on port 9187

  - job_name: 'celery_flower'
    # Celery Flower for monitoring tasks
    static_configs:
      - targets: ['celery_flower:5555'] # Celery Flower runs on port 5555
